import tkinter as tk

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black'
_tabfg2 = 'black'
_tabbg1 = 'grey75'
_tabbg2 = 'grey89'
_bgmode = 'light'

def generate():
   def generateInterface():
       top = tk.Tk()
       top.geometry("600x1+681+504")
       top.minsize(120, 1)
       top.maxsize(1924, 1061)
       top.resizable(1, 1)
       top.title("Toplevel 0")
       top.configure(background="#d9d9d9")

       Label1 = tk.Label(top)
       Label1.place(relx=0.367, rely=0.044, height=31, width=144)
       Label1.configure(anchor='w')
       Label1.configure(background="#d9d9d9")
       Label1.configure(compound='left')
       Label1.configure(disabledforeground="#a3a3a3")
       Label1.configure(foreground="#000000")
       Label1.configure(text='''MODEL DOWNLOADER''')
       menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
       top.configure(menu = menubar)

       Label2 = tk.Label(top)
       Label2.place(relx=0.233, rely=0.111, height=21, width=314)
       Label2.configure(anchor='w')
       Label2.configure(background="#d9d9d9")
       Label2.configure(compound='left')
       Label2.configure(disabledforeground="#a3a3a3")
       Label2.configure(foreground="#000000")
       Label2.configure(text='''Creates an AI model that compares faces using a pre built''')
       Label4 = tk.Label(top)
       Label4.place(relx=0.233, rely=0.156, height=21, width=304)
       Label4.configure(anchor='w')
       Label4.configure(background="#d9d9d9")
       Label4.configure(compound='left')
       Label4.configure(disabledforeground="#a3a3a3")
       Label4.configure(foreground="#000000")
       Label4.configure(text='''model run python Compare.py in the terminal or use a''')
       Label5 = tk.Label(top)
       Label5.place(relx=0.233, rely=0.2, height=21, width=314)
       Label5.configure(anchor='w')
       Label5.configure(background="#d9d9d9")
       Label5.configure(compound='left')
       Label5.configure(cursor="fleur")
       Label5.configure(disabledforeground="#a3a3a3")
       Label5.configure(foreground="#000000")
       Label5.configure(text='''code editor to use the AI after running this programmme''')
       Label3 = tk.Label(top)
       Label3.place(relx=0.05, rely=0.333, height=21, width=94)
       Label3.configure(anchor='w')
       Label3.configure(background="#d9d9d9")
       Label3.configure(compound='left')
       Label3.configure(disabledforeground="#a3a3a3")
       Label3.configure(foreground="#000000")
       Label3.configure(text='''device name''')
       Entry1 = tk.Entry(top)
       Entry1.place(relx=0.2, rely=0.333, height=20, relwidth=0.273)
       Entry1.configure(background="white")
       Entry1.configure(disabledforeground="#a3a3a3")
       Entry1.configure(font="TkFixedFont")
       Entry1.configure(foreground="#000000")
       Entry1.configure(insertbackground="black")
       Label6 = tk.Label(top)
       Label6.place(relx=0.533, rely=0.333, height=21, width=104)
       Label6.configure(anchor='w')
       Label6.configure(background="#d9d9d9")
       Label6.configure(compound='left')
       Label6.configure(disabledforeground="#a3a3a3")
       Label6.configure(foreground="#000000")
       Label6.configure(text='''learning rate''')
       Entry2 = tk.Entry(top)
       Entry2.place(relx=0.683, rely=0.333, height=20, relwidth=0.273)
       Entry2.configure(background="white")
       Entry2.configure(disabledforeground="#a3a3a3")
       Entry2.configure(font="TkFixedFont")
       Entry2.configure(foreground="#000000")
       Entry2.configure(insertbackground="black")
       Label7 = tk.Label(top)
       Label7.place(relx=0.05, rely=0.444, height=21, width=74)
       Label7.configure(anchor='w')
       Label7.configure(background="#d9d9d9")
       Label7.configure(compound='left')
       Label7.configure(disabledforeground="#a3a3a3")
       Label7.configure(foreground="#000000")
       Label7.configure(text='''epochs''')
       Entry3 = tk.Entry(top)
       Entry3.place(relx=0.2, rely=0.444, height=20, relwidth=0.273)
       Entry3.configure(background="white")
       Entry3.configure(disabledforeground="#a3a3a3")
       Entry3.configure(font="TkFixedFont")
       Entry3.configure(foreground="#000000")
       Entry3.configure(insertbackground="black")
       Label8 = tk.Label(top)
       Label8.place(relx=0.533, rely=0.444, height=21, width=84)
       Label8.configure(anchor='w')
       Label8.configure(background="#d9d9d9")
       Label8.configure(compound='left')
       Label8.configure(disabledforeground="#a3a3a3")
       Label8.configure(foreground="#000000")
       Label8.configure(text='''model name''')
       Entry4 = tk.Entry(top)
       Entry4.place(relx=0.683, rely=0.444, height=20, relwidth=0.273)
       Entry4.configure(background="white")
       Entry4.configure(cursor="fleur")
       Entry4.configure(disabledforeground="#a3a3a3")
       Entry4.configure(font="TkFixedFont")
       Entry4.configure(foreground="#000000")
       Entry4.configure(insertbackground="black")
       Text1 = tk.Text(top)
       Text1.place(relx=0.05, rely=0.533, relheight=0.387, relwidth=0.923)
       Text1.configure(background="white")
       Text1.configure(font="TkTextFont")
       Text1.configure(foreground="black")
       Text1.configure(highlightbackground="#d9d9d9")
       Text1.configure(highlightcolor="black")
       Text1.configure(insertbackground="black")
       Text1.configure(selectbackground="#c4c4c4")
       Text1.configure(selectforeground="black")
       Text1.configure(wrap="word")

       top.mainloop()

   generateInterface()

generate()

